spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/recruit
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

logging:.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace